### ISSUE TITLE
Issue with learnr

### ISSUE THREAD

**Issue by AedinMcCann** [madina-k/DSE2021_tutorials#1]
This week's tutorial is not working for me as there appears to be an issue with library('learnr'). I had this exact issue with the first week, but it was resolved when I updated RStudio. Checked for updates again, but I have the most up to date version now. 

Does anyone know a solution to this?

Here is a screenshot of my issue

![image](https://user-images.githubusercontent.com/70332806/112597315-e0f38080-8e04-11eb-99b9-b54a76cca168.png)

**Comment by madina-k** [comment]
Hi Aedin,

I think there might be two reasons why you get this error:

1. You do not have the csv file in the directory
2. Or you are trying to run the code from within an Rmd file rather than compiling the Rmd file by clicking “Run” button.

Let me know if you still have problems. (You can always connect to the tutorial on the server using the shinyapp link instead).

Best,
Madina





On 26 Mar 2021, at 08:30, AedinMcCann ***@***.******@***.***>> wrote:



This week's tutorial is not working for me as there appears to be an issue with library('learnr'). I had this exact issue with the first week, but it was resolved when I updated RStudio. Checked for updates again, but I have the most up to date version now.

Does anyone know a solution to this?

Here is a screenshot of my issue

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F70332806%2F112597315-e0f38080-8e04-11eb-99b9-b54a76cca168.png&data=04%7C01%7Cmadina.kurmangaliyeva%40eui.eu%7C2aa4d595c7df42014f3408d8f028ff64%7Cd3f434ee643c409f94aa6db2f23545ce%7C0%7C0%7C637523406171096596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1zwFNWuQ3yjFFyvZ3IV9%2BpCo0oTKdzml%2FN27S0zUAFo%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmadina-k%2FDSE2021_tutorials%2Fissues%2F1&data=04%7C01%7Cmadina.kurmangaliyeva%40eui.eu%7C2aa4d595c7df42014f3408d8f028ff64%7Cd3f434ee643c409f94aa6db2f23545ce%7C0%7C0%7C637523406171096596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QNUcl1yEXEgfxKffZtRR6IkkXaJeXvbCBuJmBFrjgis%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGBG2GQ5HUJEPRAMR5FN2NDTFQZYLANCNFSM4Z23TBAQ&data=04%7C01%7Cmadina.kurmangaliyeva%40eui.eu%7C2aa4d595c7df42014f3408d8f028ff64%7Cd3f434ee643c409f94aa6db2f23545ce%7C0%7C0%7C637523406171106591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xbIDh7tophWPpH2Exhe4Hj3pcCRIadAPqjPR1ScsftE%3D&reserved=0>.


The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination, distribution, forwarding, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited without the express permission of the sender. If you received this communication in error, please contact the sender and delete the material from any computer.
